---
- name: add proxy in /etc/environment
  become: yes
  blockinfile:
    path: /etc/environment
    block:
        HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/
        HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/
        http_PROXY=http://wwwproxy.unimelb.edu.au:8000/
        https_PROXY=http://wwwproxy.unimelb.edu.au:8000/
        no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au

# Install dependencies on the host
- name: Install pip
  become: yes
  apt:
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update; sudo apt-get install python-pip

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk==0.36.2']
    state: latest
# pip install openstacksdk

