- hosts: public
  tasks:
  - name: Create directory
    become: yes
    file:
        path: /etc/systemd/system/docker.service.d
        state: directory

  - name: Create file
    become: yes
    file:
        path: /etc/systemd/system/docker.service.d/http-proxy.conf
        state: touch

  - name: add http-proxy
    become: yes
    blockinfile:
      path: /etc/systemd/system/docker.service.d/http-proxy.conf
      block: |
        [Service]
        Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
        Environment="NO_PROXY=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
        
  - name: restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
    systemd:
      state: restarted
      daemon_reload: yes
      name: docker
        